# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      env:
        SENSO_API_URL: https://auto-loan-api.senso.ai/rate
        SENSO_API_KEY: AIzaSyCD_-qCdXqrvWGHN1tpe2PH6Rf8zpnTdXs
        TRADERAUTO_SQLDB_URL: jdbc:mysql://traderautoplusdb.cs3kq1tsgpar.ca-centr$
        TRADERAUTO_SQLDB_USER: sweatless
        TRADERAUTO_SQLDB_PWD: PaulGries123
        SENSO_API_SCORE_URL: https://auto-loan-api.senso.ai/score
        SERVER_ROOT: http://ec2-18-118-19-97.us-east-2.compute.amazonaws.com:8080
      run: gradle build
      

